### ISSUE TITLE
Tracking RunV Support in cri-o/ocid

### ISSUE THREAD

**Issue by resouer** [kubernetes-incubator/cri-o#168]
## Tracking RunV Support in cri-o/ocid

Recently we tried a little bit to play with cri-o to run runV. For those who are not familar with [runV](https://github.com/hyperhq/runv), runV is a OCI compatible runtime which leverages hypervisor as isolation sandbox. It is portable (multi-arch, multi-hypervisor) and lightweight like Linux container while secure as normal VM.

Comparing to remote runtime, cri-o + runV is straightforward and efficient. On the other hand, both cri-o and runV are young projects so there still need a lot of work to do. Since we have some experience on OCI runtime, we can help both with RunC and RunV integration. Let's begin the first step from here.

### Pod/container managment
Generally, we reached agreement that runV integration will try best to match the runC workflow including `conmon`. Thus, a light-weighted proxy will be needed to meet requirements from `conmon` side. Besides that, there are some features are expected to happen in runV side: 

- [ ] runV refratoring: the existing containerd dependency will be refactor out (but we will keep the old code for test usage) while using file-lock based management (no daemon required, follow runC style mgmt)

- [ ] stream: the host-side light-weighted proxy will handle io between hyperstart and client ( the workaround we mentioned on github for `--console-socket` of runC)

- [ ] Pod level cgroups. For hypervisor based runtime, it always requires cpu/mem set before start the sandbox, we will get these value from Pod level cgroups (https://github.com/kubernetes/kubernetes/pull/31546, and we have also implemented same thing in https://github.com/kubernetes/frakti/pull/46)

- [ ] Infra container. RunV will try best to match cri-o's workflow, so a 'useless' infra container will be launched inside RunV sandbox, but please note most of infra container's responsibilities are actually done by RunV sandbox & hyperstart (the init process inside it), see: https://github.com/kubernetes-incubator/cri-o/issues/168#issuecomment-262866122. We are also open for discussion to eliminate this infra Container, if possible. 

### runV CLI API
> Mainly reference: https://github.com/opencontainers/runtime-spec/pull/513

- [ ] runV need to split `start` to `create` and `start` (@gnawux https://github.com/hyperhq/runv/pull/295)
- [ ] Implement `delete` api

### Others
- [ ] Seprerate runV `annotations` from `labels`
- [ ] Attach/exec/port-mapping in favor of k8s CRI streaming:

> k8s CRI streaming issue & PR: 
https://github.com/kubernetes/kubernetes/issues/29579 
https://github.com/kubernetes/kubernetes/pull/35330

> streaming design doc https://docs.google.com/document/d/1OE_QoInPlVCK9rMAx9aybRmgFiVjHpJCHI9LrfdNM_s/edit?usp=sharing

- [ ] logging in favor of k8s CRI logging:

> k8s CRI logging issue & proposal:
https://github.com/kubernetes/kubernetes/issues/30709
https://github.com/kubernetes/kubernetes/pull/33111

### Network
- [ ] CNI support for hypersior based runtime is under discussion: https://github.com/containernetworking/cni/issues/251, since it still need time (at least two releases later), we are working on support bridge-based networking such as `flannel`. (claimed by: @heartlock)

/cc the authors of runV: @laijs @gao-feng

and /cc hyper + k8s community members who will help (and already helped) this work: @feiskyer @resouer @Crazykev @YaoZengzeng @xlgao-zju

**Comment by feiskyer** [comment]
@resouer Make a simple todo list for easy tracking?

**Comment by resouer** [comment]
@feiskyer Yes, we are working out a list

**Comment by cyphar** [comment]
The biggest thing I would ask is that you all make sure that you're fine with the state of opencontainers/runtime-spec#513. Conmon will follow that API once that is merged (and the corresponding runC PR -- opencontainers/runc#1018 -- is merged), because then we don't have to assume the runC API any more. Specifically, can you make sure that `--console-socket` will work for runV?

**Comment by cyphar** [comment]
Also, I'm working on fixing up conmon to come into line with opencontainers/runtime-spec#513, but I'm going to hold off on making a PR until runC merges the `--console-socket` patchset (which the other maintainers have said will be the end of this month, hopefully).

**Comment by mrunalp** [comment]
@resouer Thanks for kicking off this issue. Looking forward to working with you all. As @cyphar suggested, keep an eye on 513 for any potential issues/workaround you may need in runv.

**Comment by gao-feng** [comment]
The way to get the exit code of container is not suitable for `runv`, right now the exit code is got by `conmon` running on host, this definitely doesn't work for `runv`.

**Comment by resouer** [comment]
For all, just updated the issue description with a TODO list to track the integration status.

**Comment by jjlakis** [comment]
@feiskyer @resouer How the sandbox/container creation will be solved for cri-o+runV? Creating infra-container for sandbox and adding N containers to it will result in N+1 VMs launched which is not expected I think.

**Comment by feiskyer** [comment]
> Creating infra-container for sandbox and adding N containers to it will result in N+1 VMs launched which is not expected I think.

This is not true for runV. For runV, a sandbox is a VM, and all containers of same pod will be run in one VM.

**Comment by sameo** [comment]
@feiskyer I'm probably missing something, but how does runV know from the OCI config that a specific container is supposed to be a sandbox or not ?

**Comment by jjlakis** [comment]
+1 to @sameo's question.
Also implementation of `RunPodSanbox` in `cri-o` always creates infra-container so development is needed to provide this. Thus, shouldn't it be a part of the integration plan?

cc @pskrzyns

**Comment by cyphar** [comment]
@jjlakis It probably will be necessary to add features to runV (and to the proposed VM section of the spec) similar to Linux's namespace paths. Otherwise we won't be able to generically tell a VM-based runtime to run a process inside a VM rather than start a new one.

**Comment by laijs** [comment]
@sameo runv always launches a sandbox(vm and hyperstart agent/spawner, namespace, sandbox-pidns-init process inside the vm) when the it launches the first container including the infra-container.

but the infra-container in the vm is useless, sandbox-pidns-init process owns the namespaces instead of the pause process of the infra-container, sandbox-pidns-init is also the subreaper of the non-entry-processes. (entry-processes = oci-container/oci-process 's first process).

**Comment by resouer** [comment]
Just updated the track list about infra container, as well as pod level cgroups.

**Comment by sameo** [comment]
@laijs I'm fully aware of hyperstart's behaviour as [we're switching to it](https://github.com/01org/cc-oci-runtime/tree/redesign-for-cc-2.1) for Clear Containers as well :) I fully understand how the pause container itself is irrelevant for runV or Clear Containers.

What I don't understand is how runV will know when to start a VM and when to send a `NewContainer` command to hyperstart to actually add a container to the Pod. From an OCI compatible runtime perspective, this will look like 2 very similar commands. For example

1. `<runtime> create -c podsandbox-1 -b pause_bundle_path -p pid_file` to create (and then start) the infrastructure container
2. `<runtime> create -c container1 -b container_bundle_path -p pid_file` to create (and then start as well) a container to be running withint the pod namespaces.

with command 1 you need to create a VM that will start hyperstart and have it ready to take commands. With command 2 you must not create a VM but instead send an hyperstart `NewContainer` command to an already existing VM. From the command arguments and/or the OCI config file under the bundle path, how will runV make the distinction between case 1 and 2 ?

FYI, we're preparing a PR for Clear Containers support and as discussed with @mrunalp during LPC, we want to pass that information through ocid namespaced annotations. See [this commit](https://github.com/sameo/cri-o/commit/8a8e980f905ced190e01b2bac8183bfb2775eb72).

**Comment by sameo** [comment]
@laijs Or do you infer that a container must run on a pod by matching the networking and ipc namespaces of the container's namespace description with a pod's ones ?

**Comment by laijs** [comment]
@sameo, some changes are needed in the runtime-spec for these scenerios. Before any possible changes in the runtime-spec, cc-container can expose the (infro-)container's proxy's pid to the upper layer(cri-o or docker), when the upper layer uses the pid in the namespace path in the spec for creating the next container, the runtime(cc-container) will know the information and add the new container to the previous VM. runv may also have to follow this way and add proxy-processes.

This is just a workaround, and it would be broken in many ways. what do you think?

**Comment by sameo** [comment]
@laijs I agree only using the pid in the namespace path would be broken and really only a workaround.

With clear containers we have a proxy to arbitrate between all processes that want to access and on cc-shim for each container that we launch. As a matter of fact, when running ocid with PR #217, I can now start, stop and delete pods, and also start additional containers within that pod.

I'm using the additional annotations on the clear containers code in this branch:
https://github.com/01org/cc-oci-runtime/commits/sameo/topic/cri-o

I'd be really interested to get your feedback on PR #217 as this could also be helpful for the runV integration with CRI-O.

**Comment by cyphar** [comment]
@laijs #217 is probably a much better fix for the issue.

**Comment by mrunalp** [comment]
Closing as I assume you aren't working on this actively.
